export const blogEntriesOld = [
  {
    title: "Iceland 🇮🇸",
    coordinates: [[64.774631, -18.753533]],
  },
  {
    title: "Dubrovnik, Croatia 🇭🇷",
    coordinates: [[42.6507, 18.0944]],
  },
  {
    title: "Athens | Mykonos | Santorini, Greece 🇬🇷",
    coordinates: [
      [37.9838, 23.7275],
      [37.4415, 25.3667],
      [36.4618, 25.3753],
    ],
  },
  {
    title: "İstanbul, Turkey 🇹🇷",
    coordinates: [[41.0082, 28.9784]],
  },
  {
    title: "Cairo | Luxor, Egypt 🇪🇬",
    coordinates: [
      [30.0444, 31.2357],
      [25.6872, 32.6396],
    ],
  },
  {
    title: "Petra, Jordan 🇯🇴",
    coordinates: [[30.3285, 35.4444]],
  },
  {
    title: "Tel Aviv, Israel 🇮🇱 + Jerusalem, Israel 🇮🇱 / Palestine 🇵🇸",
    coordinates: [
      [32.0853, 34.7818],
      [31.7683, 35.2137],
      [31.559, 35.4732],
    ],
  },
  {
    title: "Agra | Delhi, India 🇮🇳",
    coordinates: [
      [27.1767, 78.0081],
      [28.7041, 77.1025],
    ],
  },
  {
    title: "Hong Kong 🇭🇰",
    coordinates: [[22.3193, 114.1694]],
  },
  {
    title: "Seoul, South Korea 🇰🇷",
    coordinates: [[37.5519, 126.9918]],
  },
  {
    title: "Beijing | Xi’an | Zhangjiajie, China 🇨🇳",
    coordinates: [
      [29.3153, 110.4348],
      [34.2658, 108.9541],
      [40.7025, 117.2337],
      [39.9042, 116.4074],
    ],
  },
  {
    title: "Taipei, Taiwan 🇹🇼",
    coordinates: [[25.033, 121.5654]],
  },
  {
    title: "Manila, Philippines 🇵🇭",
    coordinates: [[14.5995, 120.9842]],
  },
  {
    title: "Singapore 🇸🇬",
    coordinates: [[1.3521, 103.8198]],
  },
  {
    title: "Chiang Mai | Bangkok | Phuket, Thailand 🇹🇭",
    coordinates: [
      [18.7883, 98.9853],
      [13.7563, 100.5018],
      [7.8804, 98.9853],
    ],
  },
  {
    title: "Siem Reap, Cambodia 🇰🇭 ",
    coordinates: [[13.3633, 103.8564]],
  },
  {
    title: "Hanoi | Hoi An | Ho Chi Minh City, Vietnam 🇻🇳",
    coordinates: [
      [21.0278, 105.8342],
      [20.9101, 107.1839],
      [15.8801, 108.338],
      [10.8231, 106.6297],
    ],
  },
  {
    title: "Tokyo, Japan 🇯🇵",
    coordinates: [[35.6764, 139.65]],
  },
  {
    title: "Osaka, Japan 🇯🇵",
    coordinates: [[34.6937, 135.5023]],
  },
  {
    title: "Nagoya, Japan 🇯🇵",
    coordinates: [[35.1815, 136.9066]],
  },
  {
    title: "Kyoto, Japan 🇯🇵",
    coordinates: [[35.0116, 135.7681]],
  },
  {
    title: "Bogota, Colombia 🇨🇴 ",
    coordinates: [[4.711, -74.0721]],
  },
  {
    title: "Cusco | Machu Picchu, Peru 🇵🇪",
    coordinates: [
      [-13.532, -71.9675],
      [-13.1632, -72.5453],
    ],
  },
  {
    title: "Iguaçu Falls, Brazil 🇧🇷 + Iguazu Falls, Argentina 🇦🇷",
    coordinates: [[-25.6953, -54.4367]],
  },
  {
    title: "Rio de Janeiro | São Paulo | Caraguatatuba, Brazil 🇧🇷 ",
    coordinates: [
      [-22.9068, -43.1729],
      [-23.5558, -46.6396],
      [-23.6201, -45.4121],
    ],
  },
  {
    title: "Lisbon, Portugal 🇵🇹",
    folder: "/blog/2022/portugal",
    numImages: 9,
    text: "My last stop during my first trip through Europe! As I was searching for flights to go back home from Madrid, one of the cheapest options was to do a 22 hour layover in Lisbon. Seemed like a no brainer since it meant adding one more visited country to my count. \nIf Madrid made me feel reminiscent of California, Lisbon was even more so. It felt like I was already in San Francisco just instead of the Pacific Ocean, it was the Atlantic. The infamous coastal weather included!\nBy the time I was here, I felt content and ready to come back home after 5 weeks abroad. It was a spectacular trip that I will cherish for the rest of my life. Can’t wait to come back to do it all again sometime in the future!",
    location: "Torre de Belém",
    date: "November 21, 2022",
    preview: 7,
    coordinates: [[38.7223, -9.1393]],
  },
  {
    title: "Madrid, Spain 🇪🇸",
    folder: "/blog/2022/spain",
    numImages: 9,
    text: "When I was planning on how to spend the last few days of my trip after France, I was originally going to head back to London to do a few things I missed. When I saw the train seat prices I did some comparisons on flight tickets and quickly decided against it. It gave me the perfect excuse to go visit Spain! With the limited time I could only realistically visit one city so the question was Barcelona or Madrid? Madrid won solely because of Museo del Prado!\nI feel like I made the right decision as Madrid was stellar! It all felt reminiscent of California and ultimately made me feel a little homesick. I also felt a lot of the the Spanish I used to know come back almost naturally as I explored! My stop here was fairly quick, but I know I’ll be back someday as I really want to complete the Camino Frances. Something to look forward to!",
    location: "Plaza Mayor, Madrid",
    date: "November 14, 2022",
    preview: 2,
    coordinates: [[40.4168, -3.7038]],
  },
  {
    title: "Paris, France 🇫🇷",
    folder: "/blog/2022/france",
    numImages: 10,
    text: "What a magnificent city! Paris fell into the same legendary status for me like Italy did, and luckily it also delivered on all fronts.\nThe city as a whole was wayyy larger than I expected. I’m so glad I reserved extra time in Paris as there was just so much stuff to do! Everything I did while I was in Paris felt so fulfilling. Like I’ve been waiting my entire life just to experience every moment. Having authentic French pastries and fancy French cuisine. Exploring The Louvre and Orsay Museums. Being up close to the Eiffel Tower, Notre Dame, and Arc de Triomphe. All just magnificent!\nI was warned that French are a little rude towards foreigners who don’t speak the language so I did feel a bit intimidated going in. I oddly felt the most out of place during my first day in Paris. This feeling went away once I started noticing the smiles on people’s faces when I was trying to use the small amount of French I did know. After that, I felt welcomed and much more confident for the rest of my stay. I cannot wait to come back!",
    location: "Tour Eiffel",
    date: "November 2, 2022",
    preview: 3,
    coordinates: [[48.8575, 2.3514]],
  },
  {
    title: "Rome | Florence | Milan, Italy 🇮🇹 + Vatican City 🇻🇦",
    folder: "/blog/2022/italy",
    numImages: 10,
    text: "I still can’t believe I was in Italy! I’ve been wanting to visit ever since I was very young when my Dad taught me and my sister about the wonders of Ancient Rome, the impact of the Renaissance, and the importance of travel. Italy was always THE country I imagined going to when visiting Europe so it was surreal to finally be there. Hearing all the hype from other travelers I met this month made me even more excited to go and experience it all for myself!\nTo say that Italy lived up to my expectations is an understatement. The ancient architecture was so epic that I was filled with excitement whenever it was in eyesight. The art was so beautiful it brought me to tears multiple times. The food was…the food was the best I’ve ever had in my life! I am stunned by how much everything lived up to the hype, and was sad that I eventually had to leave.\nI eagerly want to head back already. I feel like I only scratched the surface and could easily spend several more weeks exploring. I want to experience everything Italy has to offer! Until that time comes, I will cherish the time I had here immensely. Grazie Italia!",
    location: "Italy",
    date: "October 27, 2022",
    preview: 6,
    coordinates: [
      [41.8967, 12.4822],
      [43.77, 11.2577],
      [45.4685, 9.1824],
    ],
  },
  {
    title: "Budapest, Hungary 🇭🇺 ",
    folder: "/blog/2022/hungary",
    numImages: 10,
    text: "Seventh stop in Europe! Budapest was breathtaking! I felt a sense of freedom multiple times whenever I was able to see lots of interesting landmarks from where I was standing, and knowing that I’d be able to visit and fully explore every location with little to no hassle. It was amazing!\nThis is also the first stop where I really felt like I wanted to stay longer. Not only due to how beautiful the city itself was, but also because of how the friends I made in Vienna and the new friends I made here in Budapest were staying in the city juuuuust a little longer. I’m re-learning that one the harder parts of traveling solo isn’t making new friends, but having to say goodbye to them.",
    location: "Budapest",
    date: "October 23, 2022",
    preview: 4,
    coordinates: [[47.4979, 19.0402]],
  },
  {
    title: "Vienna, Austria 🇦🇹 ",
    folder: "/blog/2022/austria",
    numImages: 10,
    text: "Sixth city in Europe! My time here just flew by. Maybe it’s a sign I’m going through some stops too fast? So far, my strategy has been to leave a country in the morning/afternoon in order to get to the next one in the evening but Vienna was the exception. I dedicated another day to exploring everything I wanted. It was totally worth it! \nWhat I’m going to remember most is how quickly I was able to make new friends and how expansive and beautiful the palaces were. My only wish is that I was able to see the palaces at night with friends! I found out the hard way that the only way to do that is to be in Vienna around Christmas time. Might be a fun thing to do in the future!",
    location: "Schönbrunn Palace",
    date: "October 20, 2022",
    preview: 7,
    coordinates: [[48.2081, 16.3713]],
  },
  {
    title: "Prague, Czech Republic 🇨🇿",
    folder: "/blog/2022/czechia",
    numImages: 10,
    text: "Europe stop number five! This city felt like walking in a fantasy world. The beautiful train ride in, untouched gothic architecture, maze-like cobblestone streets, and awe-inspiring views were all like nothing I have ever seen before. Just amazing! \nI was and still am a bit sad that I wasn’t able to tour the famous Prague Castle that was looming in the distance, but it just gives me all the more reason to come back and visit again!",
    location: "Prague",
    date: "October 15, 2022",
    preview: 8,
    coordinates: [[50.0875, 14.4378]],
  },
  {
    title: "Berlin, Germany 🇩🇪",
    folder: "/blog/2022/germany",
    numImages: 10,
    text: "Stop number four in Europe! I was told by a friend that you can feel the sense of freedom here, and that really ran true. Being there on Unity Day also helped a bit. There is so much recent history that’s proudly on display and the entire city just feels so modern. It was amazing!\nThank you @kd512d7 for giving me a glimpse of what life is like for an expat, sharing your travel tips, and leading us to exactly where we needed to be.",
    location: "Brandenburg Gate, Berlin",
    date: "October 10, 2022",
    preview: 2,
    coordinates: [[52.52, 13.405]],
  },
  {
    title: "Amsterdam, Netherlands 🇳🇱",
    folder: "/blog/2022/netherlands",
    numImages: 10,
    text: "If I were to move anywhere else temporarily, I think it would be here. Just for the chill atmosphere it provides. Something to consider during my next job hunt, whenever that is.",
    location: "Amsterdam",
    date: "October 6, 2022",
    preview: 2,
    coordinates: [[52.1326, 5.2913]],
  },
  {
    title: "Brussels, Belgium 🇧🇪",
    folder: "/blog/2022/belgium",
    numImages: 10,
    text: "Second stop in Europe! Such an amazing city! Really had that “European” vibe that I was searching for. Amazing food, architecture, and just a wonderful experience. Really loved how the city lit up at night!\nThank you @alxthiry for showing me around, treating me to dinner, explaining a bit of the history and politics of Belgium, and being an excellent friend.",
    location: "Grande Place, Brussels",
    date: "October 3, 2022",
    preview: 8,
    coordinates: [[50.8476, 4.3572]],
  },
  {
    title: "London, England 🇬🇧",
    folder: "/blog/2022/england",
    numImages: 10,
    text: "The first stop on my trip across Europe! I have never traveled outside of the US before so it was the perfect place to get my bearings.\nThank you @whywhyyao for housing me, being a good travel buddy, and making me feel welcome across the pond.",
    location: "Big Ben, London",
    date: "September 30, 2022",
    preview: 2,
    coordinates: [[51.5072, -0.1276]],
  },
  {
    title: "Los Angeles",
    coordinates: [[33.9422, -118.4036]],
  },
  { title: "San Francisco", coordinates: [[37.6193, -122.3816]] },
  { title: "Dallas Fort Worth", coordinates: [[32.899, -97.0336]] },
  { title: "New York City", coordinates: [[40.6446, -73.7797]] },
];
