export const blogEntriesSimple = [
  {
    title: "Iceland 🇮🇸",
    text: "This country is such a trip! Like exploring an icy, calm, and nearly untouched alien planet! The entire time I kept thinking to myself “I cannot believe people actually live here”. I later learned that the icy planet in Interstellar was filmed here so..go figure. The out-of-this-world landscapes along with the possibility of seeing the Northern Lights made Iceland the perfect place to end my westward circle around the globe.\nMy time here verrry relaxing. It’s quiet in Iceland. No metro lines. No trains. No sprawling city centers. The only real noises are the strong gusts of wind, the boisterous waterfalls, and the occasional snowfall. Just a total flip from every other place I’ve been to really. It was wonderful to unwind, sleep in, and take some day trips out of Reykjavík to see what Iceland had in store.\nI told myself that I would be content with putting a stop to my trips abroad and going back to my regular routine if I was able to visit allll these countries during my last solo trip AND experience the Northern Lights. I knew the chances were slim…you have much better luck seeing the lights in countries like Norway as some cities there are well above the Arctic Circle but I still wanted to try my luck.\nThe first few days had me losing hope due to the dense cloud coverage and low viewing probability. One night I didn’t even bother going out because the radar showed that the entire country was covered by a cloud the whole night. Despite the circumstances, on the very last night, only a few hours before my early flight back to the US, with dense cloud coverage AND only a 10% chance of seeing the aurora, a few of us ambitious folks luckily got a glimpse of the Northern Lights. Despite it being faint and only lasting a few minutes, it felt like closure. A fitting end to my 9-week trip around the world 🌏🌍🌎",
    date: "November 14, 2023",
    previewIndex: 0,
    images: [
      {
        src: "https://i.imgur.com/Sh8L889.jpeg",
        location: {
          name: "Rainbow Street",
          coordinates: {
            lat: "64°08'46.30\"N",
            long: "21°55'58.10\"W",
            link: "https://www.google.com/maps?q=loc:64.1462,-21.9328",
          },
        },
      },
      {
        src: "https://i.imgur.com/rWWtW2p.jpeg",
        location: {
          name: "Hallgrimskirkja",
          coordinates: {
            lat: "64°08'33.00\"N",
            long: "21°55'39.70\"W",
            link: "https://www.google.com/maps?q=loc:64.1425,-21.9277",
          },
        },
      },
      {
        src: "https://i.imgur.com/qSSJdeU.jpeg",
        location: {
          name: "Homes in downtown Reykjavík",
          coordinates: {
            lat: "64°08'35.90\"N",
            long: "21°55'41.90\"W",
            link: "https://www.google.com/maps?q=loc:64.1433,-21.9283",
          },
        },
      },
      // {
      //   src: "https://i.imgur.com/qZWbcAC.jpeg",
      //   location: {
      //     name: "Enjoying the Blue Lagoon",
      //     coordinates: {
      //       lat: "63°52'46.60\"N",
      //       long: "22°26'53.90\"W",
      //       link: "https://www.google.com/maps?q=loc:63.8796,-22.4483",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/KAHK5IV.jpeg",
      //   location: {
      //     name: "Farm on the drive to Þingvellir National Park",
      //     coordinates: {
      //       lat: "64°12'05.00\"N",
      //       long: "21°28'48.70\"W",
      //       link: "https://www.google.com/maps?q=loc:64.2014,-21.4802",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/ls8yOWf.jpeg",
      //   location: {
      //     name: "The boundary of the Northern American and Eurarsia tectonic plates",
      //     coordinates: {
      //       lat: "64°15'20.90\"N",
      //       long: "21°07'41.90\"W",
      //       link: "https://www.google.com/maps?q=loc:64.2558,-21.1283",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/Zs1Cwvw.png",
      //   location: {
      //     name: "Þingvallakirkja (Þingvellir church)",
      //     coordinates: {
      //       lat: "64°15'26.30\"N",
      //       long: "21°07'16.30\"W",
      //       link: "https://www.google.com/maps?q=loc:64.2573,-21.1212",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/QZu7VH4.jpg",
      //   location: {
      //     name: "Flag of Iceland within Þingvellir",
      //     coordinates: {
      //       lat: "64°15'36.00\"N",
      //       long: "21°07'20.60\"W",
      //       link: "https://www.google.com/maps?q=loc:64.26,-21.1224",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/w54QWbm.jpg",
      //   location: {
      //     name: "Gullfoss",
      //     coordinates: {
      //       lat: "64°19'30.40\"N",
      //       long: "20°07'27.10\"W",
      //       link: "https://www.google.com/maps?q=loc:64.3251,-20.1242",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/PPkWYXI.jpeg",
      //   location: {
      //     name: "Seljalandsfoss",
      //     coordinates: {
      //       lat: "63°36'55.50\"N",
      //       long: "19°59'21.20\"W",
      //       link: "https://www.google.com/maps?q=loc:63.615425,-19.9892222",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/gc32r7Q.jpeg",
      //   location: {
      //     name: "Skógafoss",
      //     coordinates: {
      //       lat: "63°31'50.50\"N",
      //       long: "19°30'46.80\"W",
      //       link: "https://www.google.com/maps?q=loc:63.5307,-19.5130056",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/1jDhKtn.jpg",
      //   location: {
      //     name: "Hálsanefshellir Cave",
      //     coordinates: {
      //       lat: "63°24'10.50\"N",
      //       long: "19°02'30.80\"W",
      //       link: "https://www.google.com/maps?q=loc:63.4029194,-19.0418917",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/IQo1CO2.jpeg",
      //   location: {
      //     name: "Reynisdrangar Basalt Cliffs",
      //     coordinates: {
      //       lat: "63°24'09.90\"N",
      //       long: "19°02'31.00\"W",
      //       link: "https://www.google.com/maps?q=loc:63.4027472,-19.0419472",
      //     },
      //   },
      // },
      // {
      //   src: "https://i.imgur.com/XJQRlOx.jpg",
      //   location: {
      //     name: "Glipse of the Northern Lights",
      //     coordinates: {
      //       lat: "64°09'45.30\"N",
      //       long: "22°00'49.60\"W",
      //       link: "https://www.google.com/maps?q=loc:64.1625833,-22.0137778",
      //     },
      //   },
      // },
    ],
    route: "iceland",
    flag: "🇮🇸",
  },
  {
    title: "Croatia 🇭🇷",
    text: "There is so much to gush about my time in Dubrovnik! The city itself is absolutely stunning due to it feeling like it’s stuck in medieval times!! It’s where a lot of Game of Thrones scenes were shot so as a HUGE fan of the show and the ASOIAF books…it was a must-see. Lokrum Island (only a 10-minute ferry ride away) was also out of this world! A nice natural getaway with an entire day's worth of outdoor activities! Oh, and it also had wild peacocks 🦚\nWhat I’m going to remember most though, is the close-knit group of friends I met while in this charming city. It’s wonderful experiencing a new country by yourself while traveling solo, but it’s an entirely different experience when you get to do so surrounded by new friends who are also solo travelers like yourself. Time seems to accelerate from all the fun you’re having. Your throat becomes sore from the interesting conversations and seemingly nonstop laughter. You need to remind yourself to capture the moment so you won’t forget the little things. In the end, you walk away mesmerized about what just happened and if you’re lucky, a new set of lifelong friends. For Dubrvonik, I was lucky.\nIt was bittersweet with each of us knowing we’d be parting our own separate ways, but I’m happy to have the memories we all made together. The world seems relatively small once you’ve been around the world. I know this won’t be the last I see any of them ☺️",
    date: "November 6, 2023",
    previewIndex: 0,
    images: [
      {
        src: "https://i.imgur.com/Ijcx6ld.jpeg",
        location: {
          name: "Dubrovnik Old City Harbor",
          coordinates: {
            lat: "42°38'30.60\"N",
            long: "18°06'44.90\"E",
            link: "https://www.google.com/maps?q=loc:42.6418194,18.1124667",
          },
        },
      },
    ],
    route: "croatia",
    flag: "🇭🇷",
  },
  {
    title: "Taiwan 🇹🇼",
    text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
    date: "August 21, 2023",
    previewIndex: 0,
    images: [
      {
        src: "https://i.imgur.com/IWAlZsi.jpeg",
        location: {
          name: "象山峯",
          coordinates: {
            lat: "25°01'38.90\"N",
            long: "121°34'34.70\"E",
            link: "https://www.google.com/maps?q=loc:25.0274806,121.5763111",
          },
        },
      },
    ],
    route: "taiwan",
    flag: "🇹🇼",
  },

  // {
  //   title: "Greece 🇬🇷",
  //   text: "Another must stop on a trip around the world! Greece is the country my dad cherished visiting the most during his youth. Hopping from island to island. Eating amazing Mediterranean cuisine. Visiting the ancient ruins of what is now our modern democracy. It felt fitting to follow in his footsteps for the final time.\nI think my favorite types of stops are ones where I can see some world renowned ruins in the morning (Acropolis), have a quick, cheap, and traditional lunch in the afternoon (some gyros), and knock out a museum or two in the evening (Acropolis Museum + National Archaeological Museum) all while taking public transit and/or walking. Athens was perfect for that! I distinctly remember loving how spoiled I felt having everything within arms reach from where I was staying. An easy stop for tourists! Extremely welcomed after being non stop traveling for 7 weeks at this point.\nThere’s tons to explore in Greece! Just hop onto a ferry and go to any of the islands within a couple hours reach! The two more popular islands are Mykonos and Santironi so I figured those would be the best to see during my first visit. What I quickly noticed upon arrival was how many couples there were. Lots of honeymooners and retirees. While the islands were okay to experience as a solo traveler, I think they would’ve been more enjoyable with @emmillenium beside me. I look forward to finding our ideal Greek island getaway together when her and I inevitably return ☺️",
  //   location: "Ακρόπολη Αθηνών",
  //   date: "October 24, 2023",
  //   imgurLink: "https://i.imgur.com/P29yYVI.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/P29yYVI.jpeg",
  //     "https://i.imgur.com/P29yYVI.jpeg",
  //     "https://i.imgur.com/P29yYVI.jpeg",
  //   ],
  //   route: "greece",
  //   flag: "🇬🇷",
  // },
  // {
  //   title: "Turkey 🇹🇷",
  //   text: "Where East meets West! Istanbul felt like such a fitting city to visit while I transitioned from Asia to Europe! It is literally the meeting point between the two continents after all! Not only is Istanbul the largest city in all of Europe, but it also used to be the capital of the Roman Empire, Constantinople! It felt so wonderful to be back in Europe after traveling to so many other unique places in the world. I had been looking forward to this stop for a while and I'm happy that Istanbul didn't disappoint!\nThe thing I'll cherish most about my time in Istanbul is the beauty of the city itself. When I first exited the metro line from the airport, my jaw dropped because of said beauty. The entire city is filled to the brim with GIGANTIC symmetrical mosques which (when you come from the USA) are extremely fascinating and unique! Virtually everywhere you go, you’ll see breathtaking views because of them. Each lookout point features hills filled with countless numbers of houses, tall spired minarets, and gigantic red and white Turkish flags waving proudly in the air! I tended to lose track of time whenever I stopped to take it all in.\nI had some ambitious day trips planned while I was here in Turkey. However, once I realized the sheer size of the entire city, I knew that those trips would have to be sidelined for a future visit. I heard road trips around the entirety of the country are fantastic! Something to look forward to during a future visit 🇹🇷",
  //   location: "Bosphorus Bridge",
  //   date: "October 18, 2023",
  //   imgurLink: "https://i.imgur.com/oX7cf7e.png",
  //   route: "turkey",
  //   flag: "🇹🇷",
  // },
  // {
  //   title: "Egypt 🇪🇬",
  //   text: "The legendary and iconic Egypt! It was an absolute treat to finally experience the wonders of ancient Egypt and more! Egypt was another one of the countries my dad visited during his youth and always praised so much while @ash4est and I were growing up. There was a magnet of the pyramids on our fridge which after looking at it almost every day during my childhood, subtly pushed me to go and see them for myself. Now, I’m finally here!\nEgypt was the first country where I hired a private guide! I wanted to treat myself to absorbing as much history as I possibly could and I’m happy I did so with Egyptologist @aahmed_essam. He made site-seeing engaging, intriguing, and effortless. I learned more than I would’ve ever done solo or with a group. It was the deluxe Egypt experience! I did make sure to have an extra day at the pyramids just to roam around by myself though. It was funny having all the hustlers trying to sell me a camel ride only to see them turn around disappointed once I showed them my photo. All part of the fun 😉\nWhile I was a tourist in the morning, I was a local by night. @bdlrhmnsy27 and I were lucky to get acquainted through our mutual friend @centlihank and I feel extremely lucky that our fates intertwined. He knew the best spots for hanging out, kicking back, and experiencing life like a modern Egyptian. I felt so much love and gratitude wherever we went due to his outgoing personality and extreme passion for making his guests feel at home. I luckily felt that during my time in Egypt, and I urge everyone to come to Egypt to experience the same.\nشكران Egypt!! You are easily one of the greats, and will continue to be for many centuries to come 🇪🇬",
  //   location: "Pyramids Of Giza, Egypt",
  //   date: "October 9, 2023",
  //   imgurLink: "https://i.imgur.com/C22H18M.jpeg",
  //   route: "egypt",
  //   flag: "🇪🇬",
  // },
  // {
  //   title: "Jordan 🇯🇴",
  //   text: "The first stop in the Middle East! Israel seemed like the perfect place to recoup after traveling for a month straight, and I guess I proved myself right! This stop was part reset, part history lesson. It marked the halfway point of my worldwide trip, so it was nice to be in a place that felt familiar yet unique.\nWhile Tel Aviv is known for its modernity and fun atmosphere, I was more interested in seeing Jerusalem - the meeting point of three major religions and cultures. When you explore the old town of Jerusalem, you see the essence of maintaining the status quo. There’s understanding and mutual respect between the Christians, Jews, and Muslims who are all living, working, and worshiping within a very small area. \nStanding in the places that are revered by so many people throughout the world made me feel empathetic and thankful that these places are open for devout pilgrims, casual believers, and curious onlookers to come and see with their own eyes. I know there’s a lot of contention in this part of the world right now, but in this particular space at this particular time, there is peace and I think that’s worth seeing and celebrating.",
  //   location: "Old City Jerusalem",
  //   date: "September 25, 2023",
  //   imgurLink: "https://i.imgur.com/u1DFZFR.png",
  //   route: "jordan",
  //   flag: "🇯🇴",
  // },
  // {
  //   title: "Palestine 🇵🇸",
  //   text: "The first stop in the Middle East! Israel seemed like the perfect place to recoup after traveling for a month straight, and I guess I proved myself right! This stop was part reset, part history lesson. It marked the halfway point of my worldwide trip, so it was nice to be in a place that felt familiar yet unique.\nWhile Tel Aviv is known for its modernity and fun atmosphere, I was more interested in seeing Jerusalem - the meeting point of three major religions and cultures. When you explore the old town of Jerusalem, you see the essence of maintaining the status quo. There’s understanding and mutual respect between the Christians, Jews, and Muslims who are all living, working, and worshiping within a very small area. \nStanding in the places that are revered by so many people throughout the world made me feel empathetic and thankful that these places are open for devout pilgrims, casual believers, and curious onlookers to come and see with their own eyes. I know there’s a lot of contention in this part of the world right now, but in this particular space at this particular time, there is peace and I think that’s worth seeing and celebrating.",
  //   location: "Old City Jerusalem",
  //   date: "September 25, 2023",
  //   imgurLink: "https://i.imgur.com/u1DFZFR.png",
  //   route: "palestine",
  //   flag: "🇵🇸",
  // },
  // {
  //   title: "Israel 🇮🇱",
  //   text: "The first stop in the Middle East! Israel seemed like the perfect place to recoup after traveling for a month straight, and I guess I proved myself right! This stop was part reset, part history lesson. It marked the halfway point of my worldwide trip, so it was nice to be in a place that felt familiar yet unique.\nWhile Tel Aviv is known for its modernity and fun atmosphere, I was more interested in seeing Jerusalem - the meeting point of three major religions and cultures. When you explore the old town of Jerusalem, you see the essence of maintaining the status quo. There’s understanding and mutual respect between the Christians, Jews, and Muslims who are all living, working, and worshiping within a very small area. \nStanding in the places that are revered by so many people throughout the world made me feel empathetic and thankful that these places are open for devout pilgrims, casual believers, and curious onlookers to come and see with their own eyes. I know there’s a lot of contention in this part of the world right now, but in this particular space at this particular time, there is peace and I think that’s worth seeing and celebrating.",
  //   location: "Old City Jerusalem",
  //   date: "September 25, 2023",
  //   imgurLink: "https://i.imgur.com/u1DFZFR.png",
  //   route: "israel",
  //   flag: "🇮🇱",
  // },
  // {
  //   title: "India 🇮🇳",
  //   text: "When I was theorizing about this entire trip months ago, India was one of the key countries that glued it all together. If you had asked me last year if I felt confident traveling to India solo, it would have been an easy “absolutely not”. It wasn’t until I was being ripped down the highway in Bangkok on the back of a GrabBike with a broken speedometer with no helmet on that I thought “Yeah you know what…maybe I should just go for a huge ass world trip to India after this” and I now here I am!\nI came for the chaos of everything (along with the sites + food of course) and got exactly what I wanted. So much so that it made me want even more! I met a few friends over the last year who gushed about how much they loved India and now after experiencing just a snippet for myself, I can already understand what they mean. \nMy biggest takeaway from India is how nice everyone is! Restaurant owners won’t be afraid to have a full-on conversation with you. Strangers won’t hesitate to help you get to your next location safely. Local tourists won’t be scared to ask where you’re from and grab a selfie. Even the eager tuk-tuk drivers, shopkeepers, and guides trying to sell themselves are very kind! Always a smile on their face even after you nicely tell them “no thank you” for the 20th time 😅 It’s a special experience that I think everyone should go to see for themselves 😉\nMy time here unfortunately was cut short due to a typhoon in Hong Kong but despite the setback, I made the most of the time I had. I eagerly await the day when I have the opportunity to visit India again. Hopefully for much longer.\nधन्यवाद India!!",
  //   location: "ताज महल - Taj Mahal, Agra",
  //   date: "September 18, 2023",
  //   imgurLink: "https://i.imgur.com/F4zlZA3.png",
  //   route: "india",
  //   flag: "🇮🇳",
  // },
  // {
  //   title: "Hong Kong 🇭🇰",
  //   text: "There is a lot to gush about Hong Kong! So much charm and convenience packed into such a small area. It can best be described as unapologetically lived in, highly functional, ultra-convenient, and a pleasant mix of Asian and Western culture.\nSome examples:\n\t• The escalators going into and out of the metro move faster than anywhere I’ve been.\n\t• Doing line transfers in the metro is as simple as walking in a straight line on the same platform; from one track to the next.\n\t• Convenience stores are plentiful to the point where you can sometimes see two or even three within the same line of sight. \n\t• Food options are a great variety of Cantonese and every East + Southeast Asian country.\nOh! and as a nice little bonus, a lot of people speak English! \nI had a wonderful time exploring Hong Kong. It was my last stop in my ~5 month (breaks included) span across East + Southeast Asia and it’s easy to say that it ended on a high note. I got to reunite with friends I’ve made over the past year in the place they call home while also meeting new ones. I got to experience a level 10 typhoon and get stuck in a country for the first time. On top of that, I got to do all the sightseeing I wanted and more because of my extra time here!\nMy only hope is that all the things I love about this city stay exactly the same for future visits. Something tells me that this sadly won’t be the case but only time will tell! Until then, I want to give a big BIG shoutout and say thank you again to my friends @edwlain, @ttyyvonneeee, @yueny43, and @kd512d7 for showing me around and helping me grow my love for Hong Kong. I’ll forever cherish the time I had here thanks to you all.",
  //   location: "Hong Kong",
  //   date: "September 11, 2023",
  //   imgurLink: "https://i.imgur.com/Bkw7oUa.jpeg",
  //   route: "hong-kong",
  //   flag: "🇭🇰",
  // },
  // {
  //   title: "South Korea 🇰🇷",
  //   text: "I knew I was gonna love Korea. but I just didn’t realize it was gonna win me over so easily. I felt the same sadness about Korea as I did with Taiwan. Always fell short of being able to visit, despite being so extremely close in the past. I was extremely happy to be here finally, and Korea delivered on all fronts.\nPart of me feels like Seoul is just hitting its stride. There’s quite a lot to do and see, and yet it still all felt so calm, orderly, and laid back. Maybe I just got lucky? Maybe it was just the change I needed after China? In any case, the less chaotic nature was noticeable, spectacular, and very welcomed. \nThe only part missing from my itinerary was going to a KPOP concert, or maybe just any concert in general (Porter/Madeon someday?). I was on the verge of attending one but decided against it. I’m sure I’ll regret this in the coming years. As a substitute, I was just able to hear Dynamite play over loudspeakers nearly everywhere I went. Not the same, but I still sang along and felt like I was in the cool music video every time it came on.\n고마워요 한국! 🫰 미국에서",
  //   location: "경복궁",
  //   date: "September 3, 2023",
  //   imgurLink: "https://i.imgur.com/ehcoV6m.jpeg",
  //   route: "south-korea",
  //   flag: "🇰🇷",
  // },
  // {
  //   title: "China 🇨🇳",
  //   text: "The best way to summarize China is that it’s BIG. The National Park in Zhangjiajie? Massive and out-of-this-world scenery with an incredible infrastructure to boot! The crowds within Xi’an? Busier than Disneyland on a holiday. The Great Wall? It was so large you could see it far into the horizon without any effort. Beijing? An absolutely gigantic city such that even with a highly optimized public transportation network, it still takes you an hour to get from one site to the next. It was wonderful to experience the absurdity of scale here. It was really like nowhere I had been before.\nI made a lot of wonderful memories during my stay here. I’m going to cherish the fun experiences I had with my new friends. I'm going to miss the spectacular and cheap Chinese food. I'm going to wonder what I did to deserve the above-and-beyond hospitality I was provided during my stay here. I’m going to continually think back on how happy strangers were to see a foreigner smile back and say hello to them in their native language. And I’m gonna say a big 谢谢 to China for allowing foreigners to come and experience the marvels of this country once again ☺️",
  //   location: "金山岭长城",
  //   date: "August 27, 2023",
  //   imgurLink: "https://i.imgur.com/4A6QjSS.jpeg",
  //   route: "china",
  //   flag: "🇨🇳",
  // },
  // {
  //   title: "Taiwan 🇹🇼",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "taiwan",
  //   flag: "🇹🇼",
  // },
  // {
  //   title: "Philippines 🇵🇭",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "philippines",
  //   flag: "🇵🇭",
  // },
  // {
  //   title: "Singapore 🇸🇬",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "singapore",
  //   flag: "🇸🇬",
  // },
  // {
  //   title: "Thailand 🇹🇭",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "thailand",
  //   flag: "🇹🇭",
  // },
  // {
  //   title: "Cambodia 🇰🇭",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "cambodia",
  //   flag: "🇰🇭",
  // },
  // {
  //   title: "Vietnam 🇻🇳",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "vietnam",
  //   flag: "🇻🇳",
  // },
  // {
  //   title: "Japan 🇯🇵",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "japan",
  //   flag: "🇯🇵",
  // },
  // {
  //   title: "Colombia 🇨🇴",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "colombia",
  //   flag: "🇨🇴",
  // },
  // {
  //   title: "Peru 🇵🇪",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "peru",
  //   flag: "🇵🇪",
  // },
  // {
  //   title: "Argentina 🇦🇷",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "argentina",
  //   flag: "🇦🇷",
  // },
  // {
  //   title: "Brazil 🇧🇷",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "brazil",
  //   flag: "🇧🇷",
  // },
  // {
  //   title: "Portugal 🇵🇹",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "portugal",
  //   flag: "🇵🇹",
  // },
  // {
  //   title: "Spain 🇪🇸",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "spain",
  //   flag: "🇪🇸",
  // },
  // {
  //   title: "France 🇫🇷",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "france",
  //   flag: "🇫🇷",
  // },
  // {
  //   title: "Vatican City 🇻🇦",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "vatican-city",
  //   flag: "🇻🇦",
  // },
  // {
  //   title: "Italy 🇮🇹",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "italy",
  //   flag: "🇮🇹",
  // },
  // {
  //   title: "Hungary 🇭🇺",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "hungary",
  //   flag: "🇭🇺",
  // },
  // {
  //   title: "Austria 🇦🇹",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "austria",
  //   flag: "🇦🇹",
  // },
  // {
  //   title: "Czechia 🇨🇿",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "czechia",
  //   flag: "🇨🇿",
  // },
  // {
  //   title: "Germany 🇩🇪",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "germany",
  //   flag: "🇩🇪",
  // },
  // {
  //   title: "Netherlands 🇳🇱",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "netherlands",
  //   flag: "🇳🇱",
  // },
  // {
  //   title: "Belgium 🇧🇪",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "belgium",
  //   flag: "🇧🇪",
  // },
  // {
  //   title: "England 🇬🇧",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "england",
  //   flag: "🇬🇧",
  // },
  // {
  //   title: "United States 🇺🇸",
  //   text: "The first stop on my trip around the world! I felt a lot of sadness being in Asia two times already and not being able to continue my trips into Taiwan. It of course had to be the first stop on my last big solo trip for the foreseeable future, and I’m so happy it finally happened!!\nI heard an endless amount of hype about Taiwan! The spectacular food, welcoming people, wonderful transit, and beautiful countryside. It’s all true and even better than I anticipated!! My time here wasn’t long, so I’m very eager and excited to visit here again in the future.\n謝謝台灣!",
  //   location: "九份",
  //   date: "August 21, 2023",
  //   imgurLink: "https://i.imgur.com/IWAlZsi.jpeg",
  //   galleryLinks: [
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //     "https://i.imgur.com/IWAlZsi.jpeg",
  //   ],
  //   route: "united-states",
  //   flag: "🇺🇸",
  // },
];
