export const techStack = {
  languages: ["python", "javascript", "typescript", "java", "cpp", "c"],
  web: [
    "nextjs",
    "react",
    "html",
    "css",
    "tailwind",
    "nodejs",
    "express",
    "flask",
  ],
  databases: [
    "mysql",
    "postgresql",
    "cassandra",
    "scylladb",
    "mongodb",
    "redis",
    "elasticsearch",
  ],
  infrastructure: [
    "aws",
    "docker",
    "nginx",
    "jenkins",
    "puppet",
    "vercel",
    "heroku",
  ],
  tools: ["git", "bash", "unix", "vscode", "intellij", "postman"],
};
