export const techIconsData = [
  {
    name: "Python",
    link: "https://www.python.org/",
    img: "python",
    type: "language",
    darkMode: false,
  },
  {
    name: "JavaScript",
    shortName: "JS",
    link: "https://ecma-international.org/publications-and-standards/standards/ecma-262/",
    img: "javascript",
    type: "language",
    darkMode: false,
  },
  {
    name: "TypeScript",
    shortName: "TS",
    link: "https://www.typescriptlang.org/",
    img: "typescript",
    type: "language",
    darkMode: false,
  },
  {
    name: "Java",
    link: "https://www.oracle.com/java/",
    img: "java",
    type: "language",
    darkMode: false,
  },
  {
    name: "Go",
    link: "https://go.dev/",
    img: "go",
    type: "language",
    darkMode: false,
  },
  {
    name: "C++",
    link: "https://isocpp.org/",
    img: "cpp",
    type: "language",
    darkMode: false,
  },
  {
    name: "C",
    link: "www.open-std.org/jtc1/sc22/wg14/",
    img: "c",
    type: "language",
    darkMode: false,
  },
  {
    name: "Next.js",
    link: "https://nextjs.org/",
    img: "nextjs",
    type: "web",
    darkMode: true,
  },
  {
    name: "React",
    link: "https://react.dev/",
    img: "react",
    type: "web",
    darkMode: false,
  },
  {
    name: "HTML",
    link: "https://html.spec.whatwg.org/",
    img: "html",
    type: "web",
    darkMode: false,
  },
  {
    name: "CSS",
    link: "https://www.w3.org/Style/CSS/",
    img: "css",
    type: "web",
    darkMode: false,
  },
  {
    name: "Tailwind",
    link: "https://tailwindcss.com/",
    img: "tailwind",
    type: "web",
    darkMode: false,
  },
  {
    name: "Node.js",
    shortName: "Node",
    link: "https://nodejs.org/",
    img: "nodejs",
    type: "web",
    darkMode: false,
  },
  {
    name: "Express",
    link: "https://expressjs.com/",
    img: "express",
    type: "web",
    darkMode: true,
  },
  {
    name: "Flask",
    link: "https://flask.palletsprojects.com/en/3.0.x/",
    img: "flask",
    type: "web",
    darkMode: false,
  },
  {
    name: "OpenCV",
    link: "https://opencv.org/",
    img: "opencv",
    type: "web",
    darkMode: false,
  },
  {
    name: "MySQL",
    link: "https://www.mysql.com/",
    img: "mysql",
    type: "database",
    darkMode: false,
  },
  {
    name: "PostgreSQL",
    shortName: "PSQL",
    link: "https://www.postgresql.org/",
    img: "postgresql",
    type: "database",
    darkMode: false,
  },
  {
    name: "Cassandra",
    // shortName: "Cass",
    link: "https://cassandra.apache.org/_/index.html",
    img: "cassandra",
    type: "database",
    darkMode: false,
  },
  {
    name: "ScyllaDB",
    shortName: "Scylla",
    link: "https://www.scylladb.com/",
    img: "scylladb",
    type: "database",
    darkMode: false,
  },
  {
    name: "MongoDB",
    // shortName: "Mongo",
    link: "https://www.mongodb.com/",
    img: "mongodb",
    type: "database",
    darkMode: false,
  },
  {
    name: "Redis",
    link: "https://redis.io/",
    img: "redis",
    type: "database",
    darkMode: false,
  },
  {
    name: "Elasticsearch",
    shortName: "ES",
    link: "https://www.elastic.co/elasticsearch",
    img: "elasticsearch",
    type: "database",
    darkMode: false,
  },
  {
    name: "Firebase",
    link: "https://firebase.google.com/",
    img: "firebase",
    type: "database",
    darkMode: false,
  },
  {
    name: "AWS",
    link: "https://aws.amazon.com/",
    img: "aws",
    type: "infrastructure",
    darkMode: true,
    darkMode2: true,
  },
  {
    name: "Vercel",
    link: "https://vercel.com/",
    img: "vercel",
    type: "infrastructure",
    darkMode: true,
  },
  {
    name: "Docker",
    link: "https://www.docker.com/",
    img: "docker",
    type: "infrastructure",
    darkMode: false,
  },
  {
    name: "NGINX",
    link: "https://www.nginx.com/",
    img: "nginx",
    type: "infrastructure",
    darkMode: false,
  },
  {
    name: "Cloudflare",
    link: "https://www.cloudflare.com/",
    img: "cloudflare",
    type: "infrastructure",
    darkMode: false,
  },
  {
    name: "Heroku",
    link: "https://www.heroku.com/",
    img: "heroku",
    type: "infrastructure",
    darkMode: false,
  },
  {
    name: "Jenkins",
    link: "https://www.jenkins.io/",
    img: "jenkins",
    type: "infrastructure",
    darkMode: false,
  },
  {
    name: "Puppet",
    link: "https://www.puppet.com/",
    img: "puppet",
    type: "infrastructure",
    darkMode: false,
  },

  {
    name: "Git",
    link: "https://git-scm.com/",
    img: "git",
    type: "tool",
    darkMode: false,
  },
  {
    name: "Bash",
    link: "https://www.gnu.org/software/bash/",
    img: "bash",
    type: "tool",
    darkMode: false,
  },
  {
    name: "Unix",
    link: "https://www.opengroup.org/membership/forums/platform/unix",
    img: "unix",
    type: "tool",
    darkMode: false,
  },
  {
    name: "VSCode",
    link: "https://code.visualstudio.com/",
    img: "vscode",
    type: "tool",
    darkMode: false,
  },
  {
    name: "IntelliJ",
    link: "https://www.jetbrains.com/idea/",
    img: "intellij",
    type: "tool",
    darkMode: false,
  },
  {
    name: "Android Studio",
    link: "https://developer.android.com/studio",
    img: "androidstudio",
    type: "tool",
    darkMode: false,
  },
  {
    name: "Postman",
    link: "https://www.postman.com/",
    img: "postman",
    type: "tool",
    darkMode: false,
  },
  {
    name: "PhotoShop",
    link: "https://www.adobe.com/products/photoshop.html",
    img: "photoshop",
    type: "tool",
    darkMode: false,
  },
  {
    name: "Resolve",
    link: "https://www.blackmagicdesign.com/products/davinciresolve",
    img: "resolve",
    type: "tool",
    darkMode: false,
  },
  {
    name: "GitHub",
    link: "https://github.com/",
    img: "github",
    type: "website",
    darkMode: true,
    darkMode2: true,
  },
  {
    name: "Gmail",
    link: "https://mail.google.com/mail/",
    img: "gmail",
    type: "website",
    darkMode: false,
  },
  {
    name: "LinkedIn",
    link: "https://www.linkedin.com/",
    img: "linkedin",
    type: "website",
    darkMode: false,
  },
];
